sudo: required
language: python
python:
- 3.5
services:
- docker
install:
- docker build --rm=true -t lice-mitochondria .
script:
- docker run -it lice-mitochondria /bin/echo "done"
notifications:
  slack:
    secure: xhc7vG6x4pDAQXpDn9eL2gTW/Vbg0xyA+FRkqHFpesPlSTo3fOmnOSgvcHo+8VsFiycnK6dIU0DrQFJapU7FYc9X70YYC7n37D3kQ3WFeefP8BYT4/huYqOsaXiom/QYjufFaLnj8EFunnUxaBHdvPyDvwO7yfY6H16RVFrd5pJjJiO/+UQb5f+4+BqtvShPbKHFnZqjNTepgMsDwQEBQPkjVky4DnXk01BMOprh1HgujFzipcajJWeUhHFZpcZUnYdnPuhJadh6Be3p9Pb7h5VubhE3s6sGBtget2ElIOm6iPovMS7lBnvNUiFTJb4wIyWjrVpAhGkvoQM+kq3s/0W+fL2CMjA+1scfDGilM2fzvzmpzBAvH/rcQGoYgBRlQLoBzjVdxRkcsME9Az00RfIJ59FqIiHynPaP9asgKUwMtSXkPwVeyw9wDd+yvKZuSCFqTmuHqXpT195pQjnQpfwSXKX27diixjhKTVKrImUdSzM193nsBrHT1yLnIfK5oLHiVVthnmbnumyhdPrlDOZquHUNpnV7jDsDBIbXlVFqBUiPtrS3suHWWtn9ayTui2iO040gu8vi70zAL4duXq/uIrz5A7lHudCOFzlsV1KLgoB/Y+3XAYEO3skxHwDP4sV89SALuaZMyKwW2HOgOJ/UU+z1m32lxi7OxqawdaQ=

